network_topology:
  localhost:
    openvswitch:
      br-ex: eth0
    eth0:
      - [ '192.168.0.1', '255.255.255.0', '192.168.0.254' ]
      - [ '172.16.0.1', '255.255.0.0' ]

openstack:
  admin:
    user: admin
    tenant: admin
    password: sscloudadmin
    email: admin@localhost
    token: 0cc90602a527c5ab3fe8
  controller: localhost
  compute:
    - localhost
  horizon:
    domain: localhost
    https:
      enable: True
      crt: /etc/sscloud/ssl/sscloud.crt
      key: /etc/sscloud/ssl/sscloud.crt
  region: regionOne
